name: template-env
channels:
  - conda-forge
dependencies:
  - sqlite
  - sqlalchemy
  - click
  - pynrrd>=1.1
  - numpy
  - scikit-image
  - pandas
  - pyqt
  - czifile
  - cmake
  - pip:
    - aicspylibczi
